_target_: pipeline.mat_invent.MatInvent

# global
rl_epoch: ${rl_epoch}
device: ${device}

# saving
save_dir: ./
save_freq: 100  # for agent model

# sampling
sample_cfg: ${sample_cfg}

topk_ratio: 0.5

# experience replay
replay: True
replay_args:
  buffer_size: 100
  sample_size: 10
  reward_cutoff: 0.1

# diversity filter
div_filter: True
df_args:
  tol: 3
  buff: 6

# finetune
finetune_cfg:
  batch_size: ${eval_size}
  accum_steps: 50  # accumulation_steps
  epochs: 3
  sigma: 0.025
