# reward for target bulk modulus = 300 GPa (single property optimization)
_target_: rewards.reward.Reward

root_dir: rewards

prop_cfg:
  - name: bulk_modulus
    calculator:
      _target_: rewards.calculators.ALIGNN
      root_dir: rewards/bulk_modulus
      task: bulk_modulus
      device: ${device}
      silent: true
    # target: 2.5 (float), descending, ascending
    target: 300.0
    minv: 0.0
    maxv: 250.0

reward_threshold: 0.8
