# reward for lower elemental price (single property optimization)
_target_: rewards.reward.Reward

root_dir: rewards

prop_cfg:
  - name: price
    calculator:
      _target_: rewards.calculators.PyMatGen
      root_dir: rewards/price
      task: price
    # target: 2.5 (float), descending, ascending
    target: descending
    minv: 50
    maxv: 500

reward_threshold: 0.8